---

- hosts: localhost
  connection: local
  tasks:
  - name: Create CloudFormation stack
    action: cloudformation stack_name="aws-workshop-{{ user_name }}" state=present region="eu-west-1" disable_rollback=false template="infrastructure-complete.template"
    args:
      template_parameters:
        KeyName: "{{ key_name }}"
        AmiId: ami-ba77c3cd
        InstanceType: t2.micro
        UserName: "{{ user_name }}"
        UserEmail: "{{ user_email }}"
      tags:
        Name: "aws-workshop-{{ user_name }}"
