---

- hosts: localhost
  connection: local
  vars:
    - ami_id: ami-828334f5
    - instance_type: t2.micro
    - region: eu-west-1
  tasks:
  - name: Create CloudFormation stack
    action: cloudformation stack_name="aws-workshop-{{ user_name }}" state=present region="{{ region }}" disable_rollback=false template="infrastructure-complete.template"
    args:
      template_parameters:
        KeyName: "{{ key_name }}"
        AmiId: "{{ ami_id }}"
        InstanceType: "{{ instance_type }}"
        UserName: "{{ user_name }}"
        UserEmail: "{{ user_email }}"
      tags:
        Name: "aws-workshop-{{ user_name }}"
